version: '3.8'
services:
  server:
    container_name: ${PROJECT_NAME}_server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'